#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

version=$(ynh_app_setting_get $app version)

#=================================================
# SPECIFIC BACKUP
#=================================================
# BACKUP OF THE APT SOURCE
#=================================================

if [ $version = "B" ]
then
	ynh_backup "/etc/apt/sources.list.d/minidlna.list"
fi

#=================================================
# BACKUP OF INOTIFY'S CONFIG
#=================================================

ynh_backup "/etc/sysctl.d/90-inotify_minidlna.conf"

#=================================================
# BACKUP OF MINIDLNA CONFIGURATION
#=================================================

ynh_backup "/etc/minidlna.conf"
