#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE FAILURE OF THE SCRIPT
#=================================================

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

version="$YNH_APP_ARG_VERSION"
app=$YNH_APP_INSTANCE_NAME

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================

ynh_app_setting_set $app version ${version:0:1}
ynh_app_setting_set $app overwrite_settings "1"

#=================================================
# CHECK THE DEBIAN'S CODENAME
#=================================================

codename=$(ynh_debian_release)
test -z "$codename" && (ynh_die "codename empty")

#=================================================
# STANDARD MODIFICATIONS
#=================================================
# FIND AND OPEN A PORT
#=================================================

# Find a free port
port=$(ynh_find_port 48200)

# Open ports
ynh_exec_fully_quiet yunohost firewall allow --no-upnp TCP $port
# Discovery Protocol SSDP for UPNP.
ynh_exec_fully_quiet yunohost firewall allow --no-upnp UDP 1900
ynh_app_setting_set $app port $port

#=================================================
# CREATE YUNOHOST.MULTIMEDIA DIRECTORY
#=================================================

ynh_multimedia_build_main_dir

#=================================================
# SPECIFIC SETUP
#=================================================
# INSTALL MINIDLNA
#=================================================

if [ ${version:0:1} = "B" ]
then
	# Install the backport version. (If you have issues with the standard version from the stable repository)
	ynh_replace_string "__CODENAME__" "$codename" ../conf/minidlna.list
	cp -a ../conf/minidlna.list /etc/apt/sources.list.d/
	ynh_apt update
	ynh_package_install -t $codename-backports minidlna
else
	# Install the standard version from debian repository
	ynh_apt update
	ynh_package_install minidlna
fi
ynh_app_setting_set $app version ${version:0:1}

#=================================================
# INCREASE INOTIFY'S LIMITS
#=================================================

# Increase the maximum number of files inotify can monitor.
cp -a ../conf/90-inotify_minidlna.conf /etc/sysctl.d/
# Then, reload the kernel configuration.
if ! IS_PACKAGE_CHECK; then
	sysctl -p /etc/sysctl.d/90-inotify_minidlna.conf
fi

#=================================================
# ADVERTISE SERVICE IN ADMIN PANEL
#=================================================

yunohost service add minidlna --log "/var/log/minidlna.log"

#=================================================
# CONFIGURE MINIDLNA
#=================================================

ynh_replace_string "^#*media_dir=.*" "media_dir=/home/yunohost.multimedia/share" /etc/minidlna.conf
ynh_replace_string "^#*port=.*" "port=$port" /etc/minidlna.conf
friendly_name="Yunohost DLNA"
ynh_app_setting_set $app friendly_name "$friendly_name"
ynh_replace_string "^#*friendly_name=.*" "friendly_name=$friendly_name" /etc/minidlna.conf
root_container="B"
ynh_replace_string "^#*root_container=.*" "root_container=$root_container" /etc/minidlna.conf
ynh_app_setting_set $app root_container "$root_container"
ynh_replace_string "^#wide_links=.*" "wide_links=yes" /etc/minidlna.conf

# Calculate and store the config file checksum into the app settings
ynh_store_file_checksum "/etc/minidlna.conf"

#=================================================
# RESTART MINIDLNA
#=================================================

ynh_systemd_action --action=restart --service_name=minidlna

#=================================================
# SEND A README FOR THE ADMIN
#=================================================

message="You can find a config file at /etc/minidlna.conf

MiniDLNA is going to serve the files present in the directory /home/yunohost.multimedia/share

Please have a look to the documentation to learn more how to use MiniDLNA, https://yunohost.org/#/app_minidlna

If you're facing an issue or want to improve this app, please open a new issue in this project: https://github.com/YunoHost-Apps/minidlna_ynh"

ynh_send_readme_to_admin --app_message="$message" --recipients="root"
