#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================
ynh_script_progression "Storing installation settings..."

ynh_app_setting_set --key=overwrite_settings --value=1
ynh_app_setting_set --key=admin_mail_html --value=1

#=================================================
# FIND AND OPEN A PORT
#=================================================
ynh_script_progression "Configuring firewall..."

# Discovery Protocol SSDP for UPNP.
yunohost firewall allow --no-upnp UDP 1900

#=================================================
# SPECIFIC SETUP
#=================================================
# CREATE YUNOHOST.MULTIMEDIA DIRECTORY
#=================================================
ynh_script_progression "Creating yunohost.multimedia directory..."

ynh_multimedia_build_main_dir

#=================================================
# INCREASE INOTIFY'S LIMITS
#=================================================
ynh_script_progression "Increasing inotify's limits..."

# Increase the maximum number of files inotify can monitor.
cp -a ../conf/90-inotify_minidlna.conf /etc/sysctl.d/
# Then, reload the kernel configuration.
if ! IS_PACKAGE_CHECK; then   # LXC doesn't allow sysctl to play with kernel options.
    sysctl -p /etc/sysctl.d/90-inotify_minidlna.conf
fi

#=================================================
# CONFIGURE MINIDLNA
#=================================================
ynh_script_progression "Configuring MiniDLNA..."

ynh_replace --match="^#*media_dir=.*" --replace="media_dir=/home/yunohost.multimedia/share" --file=/etc/minidlna.conf
ynh_replace --match="^#*port=.*" --replace="port=$port" --file=/etc/minidlna.conf
friendly_name="Yunohost DLNA"
ynh_app_setting_set --key=friendly_name --value="$friendly_name"
ynh_replace --match="^#*friendly_name=.*" --replace="friendly_name=$friendly_name" --file=/etc/minidlna.conf
root_container="B"
ynh_replace --match="^#*root_container=.*" --replace="root_container=$root_container" --file=/etc/minidlna.conf
ynh_app_setting_set --key=root_container --value="$root_container"
ynh_replace --match="^#wide_links=.*" --replace="wide_links=yes" --file=/etc/minidlna.conf

# Calculate and store the config file checksum into the app settings
ynh_store_file_checksum "/etc/minidlna.conf"

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression "Integrating service in YunoHost..."

yunohost service add "$app" --log="/var/log/$app.log" --needs_exposed_ports="1900"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app" --action="restart" --log_path="/var/log/$app.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
