#!/bin/bash

source .fonctions	# Charge les fonctions génériques habituellement utilisées dans le script

# Récupère les infos de l'application.
YNH_VERSION	# Récupère le numéro de version de Yunohost.
app=$YNH_APP_INSTANCE_NAME

# Source app helpers
source /usr/share/yunohost/helpers

port=$(sudo yunohost app setting $app port)

# Ferme les ports dans le firewall
if sudo yunohost firewall list | grep -q "\- $port$"
then
	echo "Close port $port"
	sudo yunohost firewall disallow TCP $port > /dev/null
fi
if sudo yunohost firewall list | grep -q "\- 1900$"
then
	echo "Close port 1900"
	sudo yunohost firewall disallow UDP 1900 > /dev/null
fi

# Suppression du paquet minidlna
if [ -e "/usr/sbin/minidlnad" ] || [ -e "/usr/bin/minidlnad" ]; then
	echo "Remove minidlna package"
	sudo apt-get -y purge minidlna
fi
if [ -e "/etc/apt/sources.list.d/minidlna.list" ]; then
	echo "Delete sources.list config"
	sudo rm "/etc/apt/sources.list.d/minidlna.list"
fi

# Suppression du paramètre inotify pour minidlna.
if [ -e "/etc/sysctl.d/90-inotify_minidlna.conf" ]; then
	echo "Delete kernel config"
	sudo rm "/etc/sysctl.d/90-inotify_minidlna.conf"
	# Et rechargement de la config du noyau.
	sudo sysctl --system
fi

# Retire le service du monitoring de Yunohost.
if sudo yunohost service status | grep -q minidlna	# Test l'existence du service dans Yunohost
then
	echo "Remove minidlna service"
	sudo yunohost service remove minidlna
fi

# Suppression des log
if [ -e "/var/log/minidlna.log" ]; then
	echo "Delete log"
	sudo rm "/var/log/minidlna.log"
fi

# Régénère la configuration de SSOwat
sudo yunohost app ssowatconf

echo -e "\e[0m"	# Restore normal color
