#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# MANAGE FAILURE OF THE SCRIPT
#=================================================

# Exit on command errors and treat unset variables as an error
set -eu

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

if [ ! -e _common.sh ]; then
	# Rapatrie le fichier de fonctions si il n'est pas dans le dossier courant
	sudo cp ../settings/scripts/_common.sh ./_common.sh
	sudo chmod a+rx _common.sh
fi
source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

version=$(ynh_app_setting_get $app version)
port=$(ynh_app_setting_get $app port)

#=================================================
# SPECIFIC RESTORE
#=================================================
# OPEN PORTS
#=================================================

sudo yunohost firewall allow --no-upnp TCP $port > /dev/null 2>&1
sudo yunohost firewall allow --no-upnp UDP 1900	 > /dev/null 2>&1 # Découverte SSDP pour UPNP.

#=================================================
# CREATE YUNOHOST.MULTIMEDIA DIRECTORY
#=================================================

wget -nv https://github.com/maniackcrudelis/yunohost.multimedia/archive/master.zip
unzip master.zip
sudo ./yunohost.multimedia-master/script/ynh_media_build.sh

#=================================================
# INSTALL MINIDLNA
#=================================================

if [ ${version:0:1} = "B" ]
then	# Installation de la version minidlna disponible dans backport. (En cas de problème avec la version actuelle des dépots)
	codename=$(lsb_release -a 2>/dev/null | grep Codename | cut -f 2)
	sudo cp -a ./minidlna.list /etc/apt/sources.list.d/
	sudo sed -i "s@ [a-z]*-backports@ $codename-backports@g" /etc/apt/sources.list.d/minidlna.list
	sudo apt-get update
	sudo apt-get -t $codename-backports -y install minidlna
else	# Installation de la version minidlna des dépots courants.
	sudo apt-get update
	sudo apt-get -y install minidlna
fi

#=================================================
# RESTORE INOTIFY'S CONFIG
#=================================================

sudo cp -a ./inotify /etc/sysctl.d/90-inotify_minidlna.conf
if IS_PACKAGE_CHECK; then
	sudo sysctl -p /etc/sysctl.d/90-inotify_minidlna.conf
fi

sudo cp -a ./minidlna.conf /etc/
sudo systemctl restart minidlna

#=================================================
# ENABLE SERVICE IN ADMIN PANEL
#=================================================

# Ajoute le service au monitoring de Yunohost.
sudo yunohost service add minidlna --log "/var/log/minidlna.log"
