#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# LOAD SETTINGS
#=================================================
ynh_script_progression --message="Loading settings..."

app=$YNH_APP_INSTANCE_NAME

version=$(ynh_app_setting_get --app=$app --key=version)
port=$(ynh_app_setting_get --app=$app --key=port)

#=================================================
# SPECIFIC RESTORE
#=================================================
# OPEN PORTS
#=================================================
ynh_script_progression --message="Configuring firewall..." --weight=15

ynh_exec_fully_quiet yunohost firewall allow --no-upnp TCP $port
# Discovery Protocol SSDP for UPNP.
ynh_exec_fully_quiet yunohost firewall allow --no-upnp UDP 1900

#=================================================
# CREATE YUNOHOST.MULTIMEDIA DIRECTORY
#=================================================
ynh_script_progression --message="Creating yunohost.multimedia directory..." --weight=6

ynh_multimedia_build_main_dir

#=================================================
# INSTALL MINIDLNA
#=================================================
ynh_script_progression --message="Installing minidlna" --weight=45

if [ ${version:0:1} = "B" ]
then
	# Install the backport version. (If you have issues with the standard version from the stable repository)
	codename=$(ynh_debian_release)
	ynh_restore_file --origin_path="/etc/apt/sources.list.d/minidlna.list"
	ynh_replace_string --match_string=" [a-z]*-backports" --replace_string=" $codename-backports" --target_file=/etc/apt/sources.list.d/minidlna.list
	ynh_apt update
	ynh_package_install -t $codename-backports minidlna
else
	# Install the standard version from debian repository
	ynh_apt update
	ynh_package_install minidlna
fi

#=================================================
# RESTORE INOTIFY'S CONFIG
#=================================================
ynh_script_progression --message="Restoring inotify's config..."

ynh_restore_file --origin_path="/etc/sysctl.d/90-inotify_minidlna.conf"
if ! IS_PACKAGE_CHECK   # LXC doesn't allow sysctl to play with kernel options.
then
	sysctl -p /etc/sysctl.d/90-inotify_minidlna.conf
fi

#=================================================
# RESTORE MINIDLNA CONFIGURATION
#=================================================
ynh_script_progression --message="Restoring MiniDLNA configuration..." --weight=7

# Delete the current config of minidlna, in order to replace it by the version from the backup
ynh_secure_remove --file="/etc/minidlna.conf"
ynh_restore_file --origin_path="/etc/minidlna.conf"
ynh_systemd_action --action=restart --service_name=minidlna

#=================================================
# ADVERTISE SERVICE IN ADMIN PANEL
#=================================================

yunohost service add minidlna --log "/var/log/minidlna.log"

#=================================================
# SEND A README FOR THE ADMIN
#=================================================

# Get main domain and buid the url of the admin panel of the app.
admin_panel="https://$(grep portal_domain /etc/ssowat/conf.json | cut -d'"' -f4)/yunohost/admin/#/apps/$app"

echo "You can find a config file at /etc/minidlna.conf

MiniDLNA is going to serve the files present in the directory /home/yunohost.multimedia/share

Please have a look to the documentation to learn more how to use MiniDLNA, https://yunohost.org/#/app_minidlna

You can configure this app easily by using the experimental __URL_TAG1__config-panel feature__URL_TAG2__$admin_panel/config-panel__URL_TAG3__.
You can also find some specific actions for this app by using the experimental __URL_TAG1__action feature__URL_TAG2__$admin_panel/actions__URL_TAG3__.

If you're facing an issue or want to improve this app, please open a new issue in this __URL_TAG1__project__URL_TAG2__https://github.com/YunoHost-Apps/minidlna_ynh__URL_TAG3__." > mail_to_send

ynh_send_readme_to_admin --app_message="mail_to_send" --recipients="root" --type=restore

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Restoration completed for $app" --last
