#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

version=$(ynh_app_setting_get $app version)
port=$(ynh_app_setting_get $app port)

#=================================================
# SPECIFIC RESTORE
#=================================================
# OPEN PORTS
#=================================================

ynh_exec_fully_quiet yunohost firewall allow --no-upnp TCP $port
ynh_exec_fully_quiet yunohost firewall allow --no-upnp UDP 1900 # Découverte SSDP pour UPNP.

#=================================================
# CREATE YUNOHOST.MULTIMEDIA DIRECTORY
#=================================================

ynh_multimedia_build_main_dir

#=================================================
# INSTALL MINIDLNA
#=================================================

if [ ${version:0:1} = "B" ]
then	# Installation de la version minidlna disponible dans backport. (En cas de problème avec la version actuelle des dépots)
	codename=$(ynh_debian_release)
	ynh_restore_file "/etc/apt/sources.list.d/minidlna.list"
	ynh_replace_string " [a-z]*-backports" " $codename-backports" /etc/apt/sources.list.d/minidlna.list
	ynh_apt update
	ynh_package_install -t $codename-backports minidlna
else	# Installation de la version minidlna des dépots courants.
	ynh_apt update
	ynh_package_install minidlna
fi

#=================================================
# RESTORE INOTIFY'S CONFIG
#=================================================

ynh_restore_file "/etc/sysctl.d/90-inotify_minidlna.conf"
if ! IS_PACKAGE_CHECK; then
	sysctl -p /etc/sysctl.d/90-inotify_minidlna.conf
fi

ynh_secure_remove "/etc/minidlna.conf"	# Supprime la config pour la remplacer par celle du backup
ynh_restore_file "/etc/minidlna.conf"
ynh_systemd_action --action=restart --service_name=minidlna

#=================================================
# ENABLE SERVICE IN ADMIN PANEL
#=================================================

# Ajoute le service au monitoring de Yunohost.
yunohost service add minidlna --log "/var/log/minidlna.log"

#=================================================
# SEND A README FOR THE ADMIN
#=================================================

message="You can find a config file at /etc/minidlna.conf

MiniDLNA is going to serve the files present in the directory /home/yunohost.multimedia/share

Please have a look to the documentation to learn more how to use MiniDLNA, https://yunohost.org/#/app_minidlna

If you facing an issue or want to improve this app, please open a new issue in this project: https://github.com/YunoHost-Apps/minidlna_ynh"

ynh_send_readme_to_admin --app_message="$message" --recipients="root"
