#!/bin/bash

source .fonctions	# Charge les fonctions génériques habituellement utilisées dans le script

# Récupère les infos de l'application.
YNH_VERSION	# Récupère le numéro de version de Yunohost.
if [ $ynh_version = "2.4" ]; then
	app=$YNH_APP_INSTANCE_NAME
else
	app=minidlna
fi
version=$(sudo yunohost app setting $app version)
port=$(sudo yunohost app setting $app port)

# Mise à jour du dossier yunohost.multimedia
wget -nv https://github.com/maniackcrudelis/yunohost.multimedia/archive/master.zip
unzip master.zip
sudo ./yunohost.multimedia-master/script/ynh_media_build.sh

# Mise à jour éventuelle du paquet minidlna
if [ $version = "B" ]
then	# Installation de la version minidlna disponible dans backport. (En cas de problème avec la version actuelle des dépots)
	codename=$(lsb_release -a 2>/dev/null | grep Codename | cut -f 2)
	sudo sed -i "s@__CODENAME__@$codename@g" ../conf/minidlna.list
	sudo cp -a ../conf/minidlna.list /etc/apt/sources.list.d/
	sudo apt-get update
	sudo apt-get -t $codename-backports -y install minidlna
else	# Installation de la version minidlna des dépots courants.
	sudo apt-get update
	sudo apt-get -y install minidlna
fi

# Augmentation du nombre maximum de fichiers surveillés par inotify.
sudo cp -a ../conf/90-inotify_minidlna.conf /etc/sysctl.d/
# Et rechargement de la config du noyau.
sudo sysctl --system

# Ajoute le service au monitoring de Yunohost.
sudo yunohost service add minidlna --log "/var/log/minidlna.log"

# Modifie la configuration de minidlna
CHECK_MD5_CONFIG "minidlna.conf" "/etc/minidlna.conf"	# Créé un backup du fichier de config si il a été modifié.
sudo sed -i 's@^#*media_dir=.*@media_dir=/home/yunohost.multimedia/share@' /etc/minidlna.conf
sudo sed -i "s/^#*port=.*/port=$port/" /etc/minidlna.conf
sudo sed -i "s/^#*friendly_name=.*/friendly_name=Yunohost DLNA/" /etc/minidlna.conf
sudo sed -i "s/^#*root_container=.*/root_container=B/" /etc/minidlna.conf

# Redémarre minidlna pour prendre en compte la nouvelle configuration
sudo service minidlna restart

# Régénère la configuration de SSOwat
sudo yunohost app ssowatconf
