#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS
#=================================================
ynh_script_progression --message="Retrieve arguments from the manifest"

app=${YNH_APP_INSTANCE_NAME:-$YNH_APP_ID}

#=================================================
# CHECK IF ARGUMENTS ARE CORRECT
#=================================================

#=================================================
# CHECK IF AN ACTION HAS TO BE DONE
#=================================================

if [ -e /etc/apt/sources.list.d/minidlna.list ]
then
	ynh_die "You are already using the version from backports repository." 0
fi

#=================================================
# SPECIFIC ACTION
#=================================================
# RE-INSTALL MINIDLNA FROM BACKPORTS
#=================================================
ynh_script_progression --message="Re-install minidlna from backports" --weight=9

# Remove the current version of minidlna
ynh_package_remove minidlna

# Then install the version from backports
codename=$(ynh_debian_release)
test -z "$codename" && (ynh_die "codename empty")

ynh_replace_string "__CODENAME__" "$codename" /etc/yunohost/apps/$app/conf/minidlna.list
cp -a /etc/yunohost/apps/$app/conf/minidlna.list /etc/apt/sources.list.d/
ynh_apt update
ynh_package_install -t $codename-backports minidlna

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Execution completed" --last
