#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

#=================================================
# CHECK IF ARGUMENTS ARE CORRECT
#=================================================

#=================================================
# CHECK IF AN ACTION HAS TO BE DONE
#=================================================

if [ ! -e /etc/apt/sources.list.d/minidlna.list ]
then
	ynh_die --message="You are already using the version from the stable repository." --ret_code=0
fi

#=================================================
# SPECIFIC ACTION
#=================================================
# RE-INSTALL MINIDLNA FROM STABLE
#=================================================
ynh_script_progression --message="Re-installing MiniDLNA from stable..." --weight=9

# Remove the current version of minidlna
ynh_package_remove minidlna
ynh_secure_remove --file="/etc/apt/sources.list.d/minidlna.list"

ynh_apt update
ynh_package_install minidlna

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Execution completed" --last
