#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

#=================================================
# CHECK IF ARGUMENTS ARE CORRECT
#=================================================

#=================================================
# CHECK IF AN ACTION HAS TO BE DONE
#=================================================

if [ ! -e /etc/apt/sources.list.d/minidlna.list ]
then
	ynh_die "You are already using the version from the stable repository." 0
fi

#=================================================
# SPECIFIC ACTION
#=================================================
# RE-INSTALL MINIDLNA FROM STABLE
#=================================================

# Remove the current version of minidlna
ynh_package_remove minidlna
ynh_secure_remove "/etc/apt/sources.list.d/minidlna.list"

ynh_apt update
ynh_package_install minidlna
